export const TOKEN_STORAGE_KEY = 'auth_token'
export const LAST_MSG_TS_STORAGE_KEY = 'last_message_timestamp'
export const DEVICE_ID_STORAGE_KEY = 'device_id'
export const CONNECTION_GUARD_NAME = 'connection_guard'
export const CONNECTION_GUARD_LAST_RESTART_STORAGE_KEY = 'connection_guard_last_restart_timestamp'
